php:
  build: .
  dockerfile: ./audiogene_collection/Dockerfile
  volumes:
    - ./audiogene_collection:/var/www/html
  links:
    - mysql
  ports:
    - "3000"

mysql:
  build: .
  volumes: 
    - audiogene_collection/mysql/:/var/lib/mysql
  dockerfile: ./audiogene_collection/mysql/Dockerfile
  ports:
    - "3306"
