php:
  build: .
  dockerfile: ./Dockerfile
  volumes:
    - ./:/var/www/html
  links:
    - mysql
  ports:
    - "3000:80"

mysql:
  build: .
  volumes: 
    - mysql/:/var/lib/mysql
  dockerfile: ./mysql/Dockerfile
  ports:
    - "3306"
